name: Run Postman Collections with Newman

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run JSONPlaceholder collection
        run: npm run test

      - name: Run HTTPBin collection with HTML report
        run: npm run test-httpbin

      - name: Run NASA collection with HTML report
        run: npm run test-nasa

      - name: Upload HTML report (NASA)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nasa-report
          path: newman/report.html